# It's not necessary to copy all keys to your config.
# If the key is missing in your config, "default-config.toml" will serve as a fallback
start-at-login = true
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

after-startup-command = [
  # JankyBorders
  'exec-and-forget borders active_color=0xffc3e88d inactive_color=0xff494d64 width=4.0',
]

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 6
inner.vertical = 6
outer.left = 6
outer.bottom = 6
outer.top = 6
outer.right = 6

# =======================================================
# BINDINGS
# https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# =======================================================
# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right
# All possible modifiers: cmd, alt, ctrl, shift
# All possible commands:  https://nikitabobko.github.io/AeroSpace/commands

# 'main' binding mode must be always presented
[mode.main.binding]

# APPLICATION RUNNERS
alt-ctrl-cmd-b = 'exec-and-forget open -n "/Applications/Brave Browser.app"'
alt-ctrl-cmd-enter = 'exec-and-forget open -n /Applications/WezTerm.app'
alt-ctrl-cmd-f = 'exec-and-forget open -n "/Applications/Firefox.app"'
alt-ctrl-cmd-g = 'exec-and-forget open -n "/Applications/Google Chrome.app"'
alt-ctrl-cmd-s = 'exec-and-forget open -n "/Applications/Spotify.app"'
alt-ctrl-cmd-t = 'exec-and-forget open -n /Applications/WezTerm.app'

# LAYOUTS
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# WINDOW
alt-x = 'close'
alt-shift-x = 'close-all-windows-but-current'
alt-f = 'fullscreen'
cmd-h = []                                    # DISABLE NATIVE WINDOW HIDE

# WINDOW FOCUS
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# WINDOW MOVE
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# WINDOW RESIZE
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

# WORKSPACE
alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# WOWRKSPACE FOCUS
alt-0 = 'workspace 10'
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'

# WORKSPACE MOVE WINDOW TO
alt-shift-0 = 'move-node-to-workspace 10'
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'

# CUSTOM MODES
# alt-shift-semicolon = 'mode service'
